apiVersion: v1
kind: Service
metadata:
  name: cephasops-api
spec:
  type: ClusterIP
  selector:
    app: cephasops-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
